const SHEETS = {
  EMPLOYEES: "Employees",
  USERS: "Users",
  PAYROLL: "Payroll",
  ATTENDANCE_RECORDS: "AttendanceRecords",
  INCENTIVE_LEDGER: "IncentiveLedger",
  SALARY_SCHEDULE: "SalarySchedule",
  SALARY_CHANGE_NOTIFICATIONS: "SalaryChangeNotifications",
};

const SHEET_HEADERS = {
  [SHEETS.EMPLOYEES]: [
    "employee_id",
    "first_name",
    "last_name",
    "company_email",
    "phone",
    "designation",
    "employee_type",
    "date_of_joining",
    "date_of_birth",
    "gender",
    "aadhaar_number",
    "pan_number",
    "pf_number",
    "pf_amount",
    "bank_name",
    "account_number",
    "ifsc_code",
    "base_salary",
    "hra",
    "other_allowance",
    "special_pay",
    "incentive",
    "status",
    "created_at",
    "updated_at",
  ],
  [SHEETS.USERS]: [
    "user_id",
    "employee_id",
    "email",
    "password_hash",
    "role",
    "is_active",
    "can_view_salaries",
    "last_login",
    "login_attempt",
    "created_at",
  ],
  [SHEETS.PAYROLL]: [
    "payroll_id",
    "employee_id",
    "employee_name",
    "month",
    "year",
    "working_days",
    "paid_days",
    "basic_salary",
    "hra",
    "other_allowance",
    "special_pay",
    "incentive_deduction",
    "incentive_payout",
    "gross_salary",
    "net_salary",
    "payment_status",
    "payment_date",
    "created_at",
  ],
  [SHEETS.ATTENDANCE_RECORDS]: [
    "attendance_id",
    "employee_id",
    "employee_name",
    "month",
    "year",
    "working_days",
    "paid_days",
    "extra_days",
    "created_at",
  ],
  [SHEETS.INCENTIVE_LEDGER]: [
    "ledger_id",
    "employee_id",
    "month",
    "year",
    "entry_type",
    "amount",
    "running_balance",
    "status",
    "reference",
    "transaction_date",
    "created_at",
  ],
  [SHEETS.SALARY_SCHEDULE]: [
    "salaryrev_id",
    "employee_id",
    "target_date",
    "salary",
    "status",
  ],
  [SHEETS.SALARY_CHANGE_NOTIFICATIONS]: [
    "notification_id",
    "employee_id",
    "new_salary",
    "reminder_count",
    "status",
  ],
};

module.exports = {
  SHEETS,
  SHEET_HEADERS,
};
